from textblob import TextBlob 

'''''
comments = ["Those 2 phones share the same specs with the revvl v+ 5g",
            "I have this phone it's great",
            "it only have 16gb",
            "These are essentially TCL phones -- and good ones at that. I've used the TCL 20S, and it was a great phone. If you're looking for an Android phone and don't want to pay iPhone prices, these two phones are seriously good buys.",
            "I am leaving this message for anyone here, including the uploader, who may know what's happening: (1st issue) Sometimes, when I receive a text message, the message appears at the top of all my messages. This forces me to scroll all the way to the top just to read the entire message. Also, it's indicating that it was received in December of 1969. (2nd issue) In my car, I have the option to set the 4 most important contacts on the main screen and everytime I start my car, the contacts are erased and I end up having to re-store those contacts over and over again. Never had a problem with other phones except this one. Can someone let me know what could be occurring and if it's happened to you as well?? Thanks.",
            "gracias saludos si pero no hacer nada adios😅🐁🍟🔥🧸🎶⁉️🇲🇽.",
            "Both Devices are appealing, but the only downside are the MediaTek chipsets (that chipset in the TCL Stylus, the Motorola G 5G, etc are awful!) This is a good start, but put in a Qualcomm Snapdragon !!",
            "❤️",
            "Hello, I would like to know about a Samsung product, specifically a Samsung Galaxy A52S international version. I would like to know if it is compatible with your line?",
            "No trae case?",
            "Can I use it in another country?",
            "Yo ya la tengo",
            "IS IT POSSIBLE TO TURN OFF THE 5G FEATURE ON THIS PHONE AND STICK TO 4G?",
            "Hey metro can I switch my revvlry to a a53 for 49$ pls reply",
            "Metro I'm so hyped to get the phone",
            "𝙥𝙧𝙤𝙢𝙤𝙨𝙢 🎉",
            "Thank you,👍",
            "📸 's are bad battery is too small needs to be 5G / WiFi enabled I ♥️ the size not everybody wants a 10' Tablet (8' is what I get from Samsung) maybe 2nd Gen will have better specs cause 3Gig RAM 32Gig ROM is crap (should be 4 / 64)",
            "This Samsung a53 has problems sending text messages gets stuck on sending",
            "What I hate about metro by tmobile is that current customers dont get deals on phones. I have been a customer since metro pcs. And if any deals the happened to have it's a small amount. Not a big difference.",
            "What I hate about metro by tmobile is that current customers dont get deals on phones. I have been a customer since metro pcs. And if any deals the happened to have it's a small amount. Not a big difference.",
            "What I hate about metro by tmobile is that current customers dont get deals on phones. I have been a customer since metro pcs. And if any deals the happened to have it's a small amount. Not a big difference.",
            "Bigg Happy lmfao 😂😂😂😂",
            "Feels like a scam",
            "Hey metro can't wait to get the phone on the first so happy it 49$ love your phones",
            "I’m looking to add a new line to my account and there’s is a deal on this phone for 200$ will it cost 200$ with the new line on my existing account",
            "Des",
            "Question,The Samsung Galaxy a53 is on sale for $49.99 when you switch.Is that sale only for new customers who switch carriers or for existing metro customers too?",
            "Proud of you Loco Ninja 🥷",
            "I got a new phone is the Samsung Galaxy a53 5G It’s so faster",
            "Amor muchos lunay Rocio si",
            "Te quiero muchos lunay Rocio si",
            "Te quiero mucho muchos lunay Rocio si",
            "hola este celular sirve para usarlo en otro pais o sea esta desbloqueado o solo sirve para la marca y Tmovil",
            "For some reason T-Mobile gave me a Samsung a13 Case and fits on Samsung a32 5G",
            "lol",
            "ok, so I went to Metropcs in Decatur, Alabama to complain about my phones overheating. They get too hot for me to hold. I have 2 phones with Metro and both phones overheat. I asked the staff what could be done and they were rude and were no help at all. I was yelled at after asking why not because I have had issues before and I always have to call the 800 lines to end up getting help, and they always ALWAYS send me back to a store. I am stuck with phones I can't hold because of the heat and they shut the apps off when it gets too hot then I can't seven make a call. Why would I get yelled at for something that I can't control? And why was I not helped after being a loyal customer? I was offered upgrades but how is that gonna help? Spending over $200 a piece for each phone isn't a solution. Both my phones have over 128gb. I am not settling for a lesser phone, priced more, getting yelled at, and still ending up with horrible service and still stuck with the worst phones ever. I m disabled, live alone and I need phones that work.",
            "ok, so I went to Metropcs in Decatur, Alabama to complain about my phones overheating. They get too hot for me to hold. I have 2 phones with Metro and both phones overheat. I asked the staff what could be done and they were rude and were no help at all. I was yelled at after asking why not because I have had issues before and I always have to call the 800 lines to end up getting help, and they always ALWAYS send me back to a store. I am stuck with phones I can't hold because of the heat and they shut the apps off when it gets too hot then I can't seven make a call. Why would I get yelled at for something that I can't control? And why was I not helped after being a loyal customer? I was offered upgrades but how is that gonna help? Spending over $200 a piece for each phone isn't a solution. Both my phones have over 128gb. I am not settling for a lesser phone, priced more, getting yelled at, and still ending up with horrible service and still stuck with the worst phones ever. I m disabled, live alone and I need phones that work.",
            "Es bueno para jugar fre fire",
            "I just got this one since my LGv60 got water damage. So far so good. Better than the revvl v and nord",
            "How muc if you have the military plan",
            "Kiero uno",
            "But you are beautiful",
            "Lo acabo de adquirir y vaya sorpresa que me he llevado , buen procesador , buena batería , excelente servicio este teléfono.",
            "Cuánto es economico",
            "That video was almost content free. The market for a simple flip phone usually wants *very* simple and easy to use. Let's see calling from contacts in action and navigation. The nav buttons look very small and potentially hard to hit",
            "Well if you can get your old commercials to 2018-2019 Metro stores can get to the old promos",
            "hay uno que dice cricket atras es el mismo modelo?",
            "No se traba se le pongo una memoria micro SD de 512 GB?",
            "Will this phone work with a wireless charger? Thanks.",
            "Hi I have a question about upgrading. If I'm going to upgrade my phone do I pay the retail price or do I get a cheaper price for already being a customer? I know people that switch get certain phones for free. If I were to go for say the iPhone 11 that's currently $99 if switch from another carrier. Would I an existing customer pay $99 as well or would I have to pay the retail price as if I were a new customer that's not porting in.",
            "Cómo ASER el teclado más grande de este mobil",
            "How much is this phone ?",
            "Precio??",
            "❤",
            "When will Nokia x100 phone will be getting android 12 updated",
            "Just bought this phone today but the",
            "😂😂😂 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂 love",
            "Tengo un plan de 60 dólares lo contraté el día de ayer pero no me entran las llamadas a México 😓",
            "God bless you.",
            "Sir this is a Wendy’s",
            "🙁🙁🙁🙁no",
            "🌈",
            "Love!",
            "Happy Pride Month 🏳️‍🌈",
            "Why did you delete my question? I am a customer and it was recommended to me to go to Metro's YT channel. I'm out of the country and am unable to call the toll free number. That wasn't very nice.",
            "Precio",
            "64 GB of storage Des!!!",
            "I got mine for $200 at metro.",
            "I just got this phone today from metro by T-Mobile i like this phone",
            "❤❤❤❤ ❤ I",
            "How come my lg stylo 6 is connected to my home's wifi, strong signal but I can only surf the web? I can't make calls nor text, sometimes I can text but that's only sometimes. Could it be the phone being that I am only using my laptop and my phone via wifi?",
            "That phone is similar to the REVVL V+ 5G.",
            "super phone",
            "Sir kabhi aayega india please rapey",
            "Ojalá lo vendieran en México",
            "The best part of the phone, in my opinion, is the Selfie option. Try and find a phone anywhere near this price taking selfies. Now it is true older people are not much into selfies, but there are some good looking oldies 🙂 that would enjoy the usage.",
            "They lied about the battery life it's definitely not 2 days. You can use up all of the juice within a day,at least on mine you can.",
            "How do you remove the zizo phone case I can't get it off",
            "Como se hace para ver el tv",
            "Only at metro",
            "Yo lo tengo y lo amo.",
            "I'm extremely a cheap guy 🤣 I always looking for the bargain I don't buy expensive phone 😁. But I m going to look at the metro store 😂 because my grandma she's a customer in the store 😂 hopefully I can find the. Bargain there the end of this month 😁🤠😜🙏🙏 🙏🥰",
            "Hello Métro t mobile Koman nou edem active yon téléphone plus nord n200 by li se Métro by t mobile",
            "How can we help decode a one plus nord n200 phone that was used by an aunt in the United States but she is no longer living?",
            "Dang, TCL/Alcatel is really letting smaller companies take thier share in the flip phone market to compete in smartphone circle. Respect.",
            " Zarate 2 months agoThis phone is really great I like the design of the buttons and on how they made the design and I like it because of the flash on the camera",
            "My notification and sound for text messaging does not seem to be working. I have tried to fix this, but had no luck. How do I get this to work?",
            "Hello I know I have reward cards paid why am I block through a cafeteria place where I'm paying rent and company and then I'm not I'm going to jail I need a lawyer when I'm in report report report report",
            " Zarate 2 months agoThe phone is really good I like it because of the stylus you can draw make notes or do anything with a stylus phone i’ll give this a 10 out of 10 and I wonder with 5G the apps like YouTube or Google low faster with 5G?",
            "Does this phone has stereo speakers ?",
            "What's the processing speed? Thanks!",
            "hoow’s life?! you did superb - talk you later! ;))",
            "que Sweetlovee.Monster encantan tus videos. Bendiciones hermosa Celina que Dios te cuide donde quiera los mortaleso abian apreciado tan hermosa mujer",
            "Bendiciones hermosa Celina que Dios te cuidex donde quiera que Virginee.Uno encantan tus videos.",
            "It's good as a business phone, doesn't take great pictures (especially selfies), doesn't game very well (it's TCL's 1st Stylus, maybe their next gen will be better with a Qualcomm Snapdragon chipset).",
            "If I buy any Samsung stylus would it work with this?",
            "n King 2 months agoI got the 5G one Ace",
            "n King 2 months agoHello",
            " Zarate 2 months agoWow! How much is it?",
            "I really do know that I am any kind of 'dog'??? So Metro account app here I soon come! Didn't want to , still might not, it's just so obvious the dogs are not advertising on my preferences - never; nor personalized to appear in ,or in part by my activities; they appear on purpose out of heavy duty spite, malice, envy, loathing, and hate , including those reasons, but not near limited to them ;",
            "How do I get in with WiFi? Because when I try to pay my bill, it tells me turn it off",
            "Cuando estará ya disponible en la tienda de metro?",
            "Is it better than the One Plus Nords?",
            " Zarate 2 months agoI love Motorola they have this nice feature where you have the shake the phone to enable flashlight",
            "What's the matter with it I can't get it",
            "When will this phone be available at metro stores ?",
            "Could I upgrade to this phone for free?",
            "Awesome phones",
            "Es para metro pcs o tmobile??",
            "Thank goodness Motorola kept this phone with a headphone jack and a the charger and wall brick included. I was afraid they was going to follow Apple and Samsung in removing them!",
            "What's the price on this",
            "Did you keep the NFC in the unlocked variant? It's a solid upgrade from my 2020 Motorola G Stylus (what's the price?)",
            " Zarate 2 months agoI like this phone I like the black color and Samsung made a good job on the design",
            "Is. This. 5g",
            "Samsung galaxy a13 4g No 5g",
            "Yo quiero saber el precio",
            "I bought 2 of these phones (business and personal use). It's a great phone. The 📷 is great!",
            "I have this phone and it's a great fast mid range phone. It comes with a capable 5guc Chip, when it comes to picking up better signals and more 5g it's better than my one plus 8t.",
            "We' no metro is owned by nazis",
            "Everything about this Device is solid, except for the mediatek chipset (blame that on the pandemic with the lack of Qualcomm Snapdragon available). $300 price point, because that screen is only 720 and there's no NFC (4Gig RAM 64Gig ROM should've been 6 - 126!)",
            "▶️▶️▶️▶️▶️▶️▶️▶️▶️▶️▶️▶️▶️▶️▶️",
            "Wow the Samsung galaxy a13 5g",
            "I like Samsung galaxy a32",
            "I love how Des has to make 2 of the same videos for Metro by T-Mobile and for T-Mobile",
            "I Have A Bad Feeling that this phone will easily bend and break in half",
            " Zarate 2 months agoMy friend has that phone His other one broke but I like it",
            " Zarate 2 months agoThis phone interests me I really like how they made the design it really interests me it looks like I want to own one of these well I’m a big fan of this phone I like how they made it for boost mobile and Metro by T-Mobile but I don’t use Metro by T-Mobile but that’s OK this phone still interests me I give this a 10 out of 10",
            "Wonder when next sale will be9",
            "Cool but how much?",
            "Address to Metro store near me",
            "My battery at the top right corner is red",
            "Question when i switch do i wait or can i get the phone right away?",
            "How do I change the text box theme color?",
            "Hey, How do you change the color of the chat box?",
            "Mm buenas quisiera saber cuánto carga sus wats",
            "Yes Samsung galaxy a03s",
            "How do you LOG OFF the app? There's no option listed on the app's dashboard?",
            "@Metro byT-Mobile Why has the Galaxy A52g along with the A32g been discontinued? I just purchased the A52g and it was delivered yesterday, should I send it back and get an S10?",
            "Alguien sabe como enviar futuros mensajes de texto?",
            "One question if I would buy this phone and switch to another place is it still usable in that place",
            "I like it I wish I can exchange",
            "Hi I have a question how to turn on fast charging",
            "Cuánto cuesta",
            "Who is this voice actress?",
            "Hello, just want to ask is that Openline? Can use in other countries like Philippines?",
            "Hey Des it's Cayden When will T Mobile Released to: Android 12 update. What will that be in this year.",
            "P.S. better stock up on those chargers because Samsung no longer has them in them in the box!",
            "Bring on the A33 5G next (the specs are almost equal to the A53 except for the cameras and it's got the headphone jack) 👍🏻",
            "Samsung galaxy a53 5g because is no headphone jack fast battery",
            "Nice",
            "buenas quiero saber si aqui en rd consigo el desbloqueo",
            "Why do they keep saying 'premium materials' when the entire laptop is made of plastic with an evident screen wobble and keyboard deck flex?",
            "Lo tengo pero no puedo liberarlo de ninguna forma ayuda como puedo liberarlo o ponerle un chip de t mobile si es metro pcs o si compro un chip americano que me agarre aquí en México",
            "I have the black Samsung Galaxy A32 5G",
            "Hola",
            "I just talked to my son who got this phone and he was trying to set it up with the fingerprint thing and he accidentally turned the phone off while doing this and now he's locked out of the phone and can't get back into it and everybody says there's no way of unlocking it can anybody help",
            "The Samsung galaxy a52 5g is fast battery",
            "I'm surprised this was released February",
            "HORRIBLE FEATURE! CANT ANSWER ANY CALLS! CANT DISABLE! BLOCKS 'ALL' CALLS! METRO PCS WONT HELP, WEBSITE WONT HELP, CALLING METRO PCS WONT STOP IT. F YOU METRO.",
            "So-so I'm with T-Mobile so you're made by T-Mobile or did you make T-Mobile?",
            "It's honestly terrible I'm switching to iPhone I'm getting a iPhone SE 3rd gen this phone is absolute terrible camera quality is like using a Samsung S5 so no improvement there and the only good thing about it it's that it's battery power is amazing but still not worth it r reccomend getting an iPhone 8 way better camera quality for an old phone like the 8 to be competing with this new phone just proves apple is better and more efficient mYeb not affordable but the SE and ipods are extremely cheap and amazing for the price of this",
            "Is metros s21 FE variant dual sim?",
            "do the stores sell all colors? only black is shown on the site",
            "Buscar mi valance",
            "Ibpuedo jugar fornite",
            "Yo lo tengo",
            "Porque mi teléfono dice que tiene dos líneas y dos números si solo tengo uno si solo tengo",
            "Yo quiero Cambiar mi número Ya que me Hackearon mi Número :(",
            "Pero se me olvidó mi contraseña de 8 digitos",
            "I'm used to gently swiping w three fingers to screenshot. This is impossible. Is there an easier way then failing hitting power and volume? Thank you.",
            "Sup Metro! 😘",
            "LG inc.",
            "Thank You!",
            "White.",
            "Stylus 6",
            "Marcus G. Harrison",
            "I Have a Question. When Will The Moto G Stylus ",
            "Not tomorrow by",
            "I can't find a custom phone case creator for the phone",
            "Will this phone get android 12",
            "Just got this phone brand new and I love it! It's a big upgrade from my A20",
            "No recueldo mi. Cuenta para asel mi pago",
            "Asil un pago",
            "Purchased this phone today and I am pleased. The camera display is awesome.",
            "How much is it",
            "Great value phone and 5G!",
            "1 07 20",
            "Wow that's TCL 30 xe 5g it's beautiful",
            "just tell people it's got a MediaTek and not a Qualcomm Snapdragon chipset!",
            "How much is it",
            "I was expecting better specs",
            "Bro happy",
            "Enjoy!",
            "It's not even on the website ?",
            "Where can I purchase a case for my REVVl V 4g phone",
            "Wow that's Moto g pure",
            "I wouldn't buy another thing from T-Mobile",
            "Hector provides",
            "All i need to know will it do more than 2g/3g I'm thru Metro pcs",
            "How much is the smartwatch plan for this?",
            "I Brought A Motorola E4 For Metropcs It's Good Phone But My Motorola Phone Has No Service/Emergency Calls Only",
            "MetroPCS T-Mobile",
            "Hey metro how long is the 30 dollar off Acp discount gonna last?",
            "But how come the camera from the bottom doesn't work at all🤨🤔 only the middle one works 🤔",
            "I have that phone 📱",
            "How the hell do i log out? there is no freaking button!",
            "Can this connect to 5ghz wifi",
            "On the Metro site it states that the display is TFT not amolid.",
            "I gotta know if I switch from iPhone 8 to this phone is it worth it?",
            "Have a extra phone ? I'm using the Galaxy Core Prime",
            "How much is it",
            "That deal is gone now",
            "Wow that's a new samsung galaxy a03s like just samsung galaxy a02s",
            "The samsung galaxy a13 5g fast charging battery",
            "Como puedo recuperar mis 8 dígitos que no recuerdo",
            "that's samsung galaxy a03s",
            "No charger in the box 🤣🤦",
            "Please note : As new as this phone is, it does not have a screen mirror option. It does have a cast option but that means you can only cast your phone to a chromecast or roku tv. This is",
            "Precio",
            "Precio$$",
            "Does this phone had 5g on on it I’m from Philadelphia pa we have 5g here",
            "How do you login out of the app? Looked for logging out can't find it.",
            "Anybody has it i have a A51 is it worth buying it?",
            "Yo viendo esto con esa tablet🤣🤣",
            "Tell me please, is it worth taking this tablet, does it lag and is it worth taking it for surfing the Internet, watching videos on YouTube and for movies and books? and is it worth the money and is it buggy or not or not much?",
            "Tell me please, is it worth taking this tablet, does it lag and is it worth taking it for surfing the Internet, watching videos on YouTube and for movies and books? and is it worth the money and is it buggy or not or not much?",
            "This dude is grossing me out..",
            "I miss the galaxy a11",
            "Wow that's nice a Samsung galaxy a51",
            "Is this better than the ACE",
            "nice",
            "When will this phone be available to purchase? It's not on the website 😕",
            "😂😂😂😂 All of this an no earplugs to come with it 😔",
            "Metro never had that phone where i lives but how do i get it",
            "How much is it I might buy this",
            "Nokia low specs but so fast and reliable and so durable much better than Chinese phone👈",
            "nice",
            "Hola una pregunta yo me quiero comprar el iPhone 13 pro pero hace tres meses me compre el 13 normal en metro quisiera saber si ustedes aceptan q le de el iPhone 13 y un poco mas de dinero por el 13 pro o pro max o eso no se puede hacer?",
            "Brand new phone with NO 5G capability. WOW 😳!",
            "That is the samsung galaxy s21 fe just like s20 fe",
            "Yes!",
            "Background music too loud !!!! Thanks goodness for Cc",
            "Wow nice phone",
            "T-Mobile continues to be awesome while Joe Biden and corrupt politicians trip over a cordless phone. Let's go Brandon.",]
'''''

comments = ["Good 😍👌", "I have filed Consumer Reporting for Fraud from TMobile. Elderly Do Not Trust this Company. They sold a phone and charged full price unauthorized onto my credit card. Then did not take care of the issue. Even admitted fault. Next to get ahold of someone not international and to talk to a manager, they denied. Now in a law suit!!  FRAUD FRAUDULENT.  Also very short answered to watch what they say because they admitted fault. Please do not trust this company!!!!"]

# def ge    t_sentiment():
#     pr    ocessed_text = TextBlob(comments)
#     polarity = processed_text.polarity
#     print(polarity)

def polarity():
    for i in comments:
        processed_text = TextBlob(i)
        polarity = processed_text.polarity

        print(polarity)

def subjectivity():

    for i in comments:
        processed_text = TextBlob(i)
        subjectivity = processed_text.subjectivity

        print(subjectivity)

polarity()

